[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "fly/functions"
  node_bundler = "esbuild"

[build.processing.html]
  pretty_urls = false

[[edge_functions]]
  function = "relay"
  path = "/*"
